# Change these first
owner: zeit-ia # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Nira
    url: https://nira.zeit.com.br
    maxResponseTime: 1000
  - name: Nira (API)
    url: https://nira.zeit.com.br/api/actuator/health
    maxResponseTime: 1000
  - name: Zeit Agro
    url: https://agro.zeit.com.br
    maxResponseTime: 5000

assignees:
  - debling
  - alissonbk

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: zeit.com.br
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/zeit-ia/zeit-ia.github.io/refs/heads/main/src/shared-images/zeit.svg
  name: Zeit Status
  theme: ocean
  introTitle: Status dos serviços Zeit
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
#
i18n:
  activeIncidents: Incidentes Ativos
  allSystemsOperational: Todos os serviços estão operando normalmente
  incidentReport: "Relatório do incidente nº $NUMBER →"
  activeIncidentSummary: Aberto em $DATE com $POSTS publicações
  incidentTitle: Detalhes do Incidente $NUMBER
  incidentDetails: Detalhes do Incidente
  incidentFixed: Resolvido
  incidentOngoing: Em andamento
  incidentOpenedAt: Aberto em
  incidentClosedAt: Fechado em
  incidentViewOnGitHub: Ver e acompanhar no GitHub
  incidentCommentSummary: Publicado em $DATE por $AUTHOR
  incidentBack: ← Voltar para todos os incidentes
  pastIncidents: Incidentes Passados
  pastIncidentsResolved: Resolvido em $MINUTES minutos com $POSTS publicações
  liveStatus: Status em Tempo Real
  overallUptime: "Tempo de atividade total: $UPTIME"
  overallUptimeTitle: Tempo de atividade total
  averageResponseTime: "Tempo médio de resposta: $TIMEms"
  averageResponseTimeTitle: Tempo médio de resposta
  sevelDayResponseTime: Tempo de resposta de 7 dias
  responseTimeMs: Tempo de resposta (ms)
  up: Online
  down: Offline
  degraded: Degradado
  ms: ms
  loading: Carregando
  navGitHub: GitHub
  footer: Esta página é [código aberto]($REPO), possibilitado por [Upptime](https://upptime.js.org)
  rateLimitExceededTitle: Limite de requisições excedido
  rateLimitExceededIntro: Você excedeu o número de requisições permitidas por hora e precisará aguardar antes de acessar este site novamente. Alternativamente, você pode adicionar um Token de Acesso Pessoal do GitHub para continuar usando o site.
  rateLimitExceededWhatDoesErrorMean: O que significa este erro?
  rateLimitExceededErrorMeaning: Este site usa a API do GitHub para acessar dados em tempo real sobre o status dos nossos serviços. Por padrão, o GitHub permite 60 requisições por hora por endereço IP — e você atingiu esse limite.
  rateLimitExceededErrorHowCanFix: Como posso corrigir isso?
  rateLimitExceededErrorFix: Você pode aguardar uma hora para que o limite do seu endereço IP seja restaurado. Alternativamente, pode adicionar seu Token de Acesso Pessoal do GitHub, que concede até 5.000 requisições por hora.
  rateLimitExceededGeneratePAT: Saiba como gerar um Token de Acesso Pessoal
  rateLimitExceededHasSet: Você já possui um token de acesso pessoal configurado.
  rateLimitExceededRemoveToken: Remover token
  rateLimitExceededGitHubPAT: Token de Acesso Pessoal do GitHub
  rateLimitExceededCopyPastePAT: Copie e cole seu token
  rateLimitExceededSaveToken: Salvar token
  errorTitle: Ocorreu um erro
  errorIntro: Ocorreu um erro ao tentar obter os detalhes mais recentes do status.
  errorText: Você pode tentar novamente em alguns instantes.
  errorHome: Ir para a página inicial
  pastScheduledMaintenance: Manutenções Programadas Anteriores
  scheduledMaintenance: Manutenção Programada
  scheduledMaintenanceSummaryStarted: Iniciada em $DATE por $DURATION minutos
  scheduledMaintenanceSummaryStarts: Inicia em $DATE por $DURATION minutos
  startedAt: Iniciado em
  startsAt: Inicia em
  duration: Duração
  durationMin: $DURATION minutos
  incidentCompleted: Concluído
  incidentScheduled: Agendado
  duration24H: 24h
  duration7D: 7d
  duration30D: 30d
  duration1Y: 1a
  durationAll: todos
  locale: pt-BR
